<?php

return [
    [
        "title" => "Luxury Apartment with Ocean View",
        "description" => "Beautifully furnished apartment overlooking the ocean.",
        "num_of_rooms" => 3,
        "num_of_beds" => 2,
        "num_bathrooms" => 2,
        "square_meters" => 120,
        "full_address" => "Via Tommaso Rook, Pisa",
        "lat" => 43.71824747491754,
        "long" => 10.373659451312106,
        "price" => 520,
        "img" => ''
    ],
    [
        "title" => "Modern City Center Loft",
        "description" => "Sleek and contemporary loft in the heart of the city.",
        "num_of_rooms" => 2,
        "num_of_beds" => 1,
        "num_bathrooms" => 1,
        "square_meters" => 80,
        "full_address" => "Via Traversa Che Guevara, Pisa",
        "lat" =>  43.74514853213075,
        "long" => 10.388608813262628,
        "price" => 300,
        "img" => ''
    ],
    [
        "title" => "Charming Countryside Cottage",
        "description" => "Quaint cottage surrounded by lush greenery and peaceful atmosphere.",
        "num_of_rooms" => 4,
        "num_of_beds" => 3,
        "num_bathrooms" => 2,
        "square_meters" => 150,
        "full_address" => "Via dei Sepolcri, Pisa",
        "lat" =>  43.6964235347685,
        "long" => 10.417038500532348,
        "price" => 600,
        "img" => ''
    ],
    [
        "title" => "Seaside Villa with Private Pool",
        "description" => "Spacious villa with stunning ocean views and a private pool.",
        "num_of_rooms" => 5,
        "num_of_beds" => 4,
        "num_bathrooms" => 3,
        "square_meters" => 200,
        "full_address" => "Via Benedetto Croce, , Pisa",
        "lat" => 43.71039338828906,
        "long" => 10.404005646137943,
        "price" => 700,
        "img" => ''
    ],
    [
        "title" => "Cosy Mountain Cabin Retreat",
        "description" => "Rustic cabin nestled in the mountains, perfect for a serene getaway.",
        "num_of_rooms" => 2,
        "num_of_beds" => 1,
        "num_bathrooms" => 1,
        "square_meters" => 70,
        "full_address" => "Viale delle Cascine, Pisa",
        "lat" =>  43.72052085057006,
        "long" => 10.358051592166627,
        "price" => 200,
        "img" => ''
    ],
    [
        "title" => "Urban Studio Apartment",
        "description" => "Compact and stylish studio apartment in the bustling city center.",
        "num_of_rooms" => 1,
        "num_of_beds" => 1,
        "num_bathrooms" => 1,
        "square_meters" => 50,
        "full_address" => "Via Camillo Guidi, Pisa",
        "lat" =>  43.65939147759814,
        "long" => 10.283416046546925,
        "price" => 150,
        "img" => ''
    ],
    [
        "title" => "Historic Townhouse in the Old Town",
        "description" => "Elegant townhouse with classic architecture and modern amenities.",
        "num_of_rooms" => 4,
        "num_of_beds" => 3,
        "num_bathrooms" => 2,
        "square_meters" => 180,
        "full_address" => "Via di Gualduccio, Pisa",
        "lat" =>  43.67099812596552,
        "long" => 10.278129544336132,
        "price" => 500,
        "img" => ''
    ],
    [
        "title" => "Sunny Beachfront Condo",
        "description" => "Bright and airy condo steps away from the sandy beach.",
        "num_of_rooms" => 3,
        "num_of_beds" => 2,
        "num_bathrooms" => 2,
        "square_meters" => 100,
        "full_address" => "Via delle Torri,Pisa",
        "lat" =>  43.70720834590505,
        "long" => 10.432780208834568,
        "price" => 350,
        "img" => ''
    ],
    [
        "title" => "Riverside Townhome with Garden",
        "description" => "Comfortable townhome overlooking the river with a beautiful garden.",
        "num_of_rooms" => 3,
        "num_of_beds" => 2,
        "num_bathrooms" => 2,
        "square_meters" => 130,
        "full_address" => "Via G. Puccini, Ghezzano",
        "lat" =>  43.727615127505295,
        "long" => 10.446799696887668,
        "price" => 450,
        "img" => ''
    ],
    [
        "title" => "Penthouse Suite with Skyline Views",
        "description" => "Luxurious penthouse offering panoramic views of the city skyline.",
        "num_of_rooms" => 5,
        "num_of_beds" => 4,
        "num_bathrooms" => 3,
        "square_meters" => 220,
        "full_address" => "Via Giuseppe Moruzzi,Pisa",
        "lat" =>   43.719159539685386,
        "long" => 10.424692981614763,
        "price" => 600,
        "img" => ''
    ],
    [
        "title" => "Oceanview Retreat",
        "description" => "Peaceful retreat with stunning views of the ocean.",
        "num_of_rooms" => 2,
        "num_of_beds" => 1,
        "num_bathrooms" => 1,
        "square_meters" => 90,
        "full_address" => "Via Angelo Battelli, Pisa",
        "lat" =>   43.72147053933051,
        "long" => 10.412565872590427,
        "price" => 300,
        "img" => ''
    ],
    [
        "title" => "City Center Penthouse",
        "description" => "Luxurious penthouse in the heart of the city with panoramic city views.",
        "num_of_rooms" => 4,
        "num_of_beds" => 3,
        "num_bathrooms" => 2,
        "square_meters" => 180,
        "full_address" => "Via Maiorca,Pisa",
        "lat" =>   43.67663543617843,
        "long" =>  10.274167270276019,
        "price" => 550,
        "img" => ''
    ],
    [
        "title" => "Lakefront Cottage",
        "description" => "Cozy cottage situated on the shores of a serene lake.",
        "num_of_rooms" => 3,
        "num_of_beds" => 2,
        "num_bathrooms" => 1,
        "square_meters" => 110,
        "full_address" => "Via della Sofina,Pisa",
        "lat" =>   43.63526264913449,
        "long" =>  10.3642607834347,
        "price" => 400,
        "img" => ''
    ],
    [
        "title" => "Rustic Farmhouse Getaway",
        "description" => "Charming farmhouse surrounded by rolling hills and picturesque countryside.",
        "num_of_rooms" => 5,
        "num_of_beds" => 4,
        "num_bathrooms" => 3,
        "square_meters" => 200,
        "full_address" => "Via le Rene, Pisa",
        "lat" =>  43.68372915942565,
        "long" => 10.422302143334969,
        "price" => 650,
        "img" => ''
    ],
    [
        "title" => "Downtown Loft with City Views",
        "description" => "Modern loft apartment with floor-to-ceiling windows offering panoramic city views.",
        "num_of_rooms" => 2,
        "num_of_beds" => 1,
        "num_bathrooms" => 1,
        "square_meters" => 85,
        "full_address" => "Via Giuseppe Mazzini, Pisa ",
        "lat" =>  43.71456364656329,
        "long" => 10.399009414306246,
        "price" => 250,
        "img" => ''
    ],
    [
        "title" => "Coastal Retreat",
        "description" => "Relaxing retreat by the coast with access to private beach.",
        "num_of_rooms" => 4,
        "num_of_beds" => 3,
        "num_bathrooms" => 2,
        "square_meters" => 160,
        "full_address" => "Via Roma, Pisa",
        "lat" =>  43.721641393798656,
        "long" => 10.395709671821313,
        "price" => 550,
        "img" => ''
    ],
    [
        "title" => "Luxury Ski Chalet",
        "description" => "Exquisite ski chalet with stunning mountain views and direct access to ski slopes.",
        "num_of_rooms" => 6,
        "num_of_beds" => 5,
        "num_bathrooms" => 4,
        "square_meters" => 250,
        "full_address" => "Via Orazio Gentileschi, Pisa",
        "lat" =>  43.72754707194224,
        "long" => 10.39766651869493,
        "price" => 700,
        "img" => ''
    ],
    [
        "title" => "Riverside Apartment with Terrace",
        "description" => "Spacious apartment overlooking the river with a large terrace for outdoor dining.",
        "num_of_rooms" => 3,
        "num_of_beds" => 2,
        "num_bathrooms" => 2,
        "square_meters" => 120,
        "full_address" => "Via del Cuore, Pisa",
        "lat" =>  43.716121670774946,
        "long" => 10.405491938021859,
        "price" => 350,
        "img" => ''
    ],
    [
        "title" => "Sunny Garden Villa",
        "description" => "Beautiful villa with lush gardens, perfect for outdoor relaxation.",
        "num_of_rooms" => 4,
        "num_of_beds" => 3,
        "num_bathrooms" => 2,
        "square_meters" => 180,
        "full_address" => "Via San Paolo, Pisa",
        "lat" =>  43.713790322369725,
        "long" =>   10.395349839877245,
        "price" => 600,
        "img" => ''
    ],
    [
        "title" => "Mountain View Retreat",
        "description" => "Tranquil retreat nestled in the mountains with breathtaking views.",
        "num_of_rooms" => 3,
        "num_of_beds" => 2,
        "num_bathrooms" => 2,
        "square_meters" => 130,
        "full_address" => "Via Giordano Bruno, Pisa",
        "lat" =>  43.711809372664504,
        "long" => 10.403833778493084,
        "price" => 450,
        "img" => ''
    ],
    [
        "title" => "Seaside Townhouse",
        "description" => "Modern townhouse just steps away from the beach with panoramic sea views.",
        "num_of_rooms" => 4,
        "num_of_beds" => 3,
        "num_bathrooms" => 2,
        "square_meters" => 160,
        "full_address" => "Via Emilia , Pisa",
        "lat" =>  43.694028633452454,
        "long" => 10.413966139875898,
        "price" => 500,
        "img" => ''
    ],
    [
        "title" => "Urban Luxury Loft",
        "description" => "Stylish loft apartment in a prime urban location with modern amenities.",
        "num_of_rooms" => 2,
        "num_of_beds" => 1,
        "num_bathrooms" => 1,
        "square_meters" => 90,
        "full_address" => "Via delle Belle Torri, Pisa",
        "lat" =>  43.71598543458901,
        "long" => 10.404763724531382,
        "price" => 300,
        "img" => ''
    ],
    [
        "title" => "Countryside Manor",
        "description" => "Grand manor house set amidst sprawling countryside estate.",
        "num_of_rooms" => 8,
        "num_of_beds" => 6,
        "num_bathrooms" => 4,
        "square_meters" => 350,
        "full_address" => "Via San Martino, Pisa",
        "lat" => 43.714094357168264,
        "long" => 10.403341893839226,
        "price" => 800,
        "img" => ''
    ],
    [
        "title" => "Lakefront Chalet",
        "description" => "Charming chalet overlooking a tranquil lake, ideal for nature lovers.",
        "num_of_rooms" => 3,
        "num_of_beds" => 2,
        "num_bathrooms" => 1,
        "square_meters" => 100,
        "full_address" => "Via Ulisse Dini, Pisa",
        "lat" => 43.71882452944517,
        "long" => 10.401213655223573,
        "price" => 400,
        "img" => ''
    ],
    [
        "title" => "Sleek City Apartment",
        "description" => "Modern apartment in the heart of the city, close to all amenities and attractions.",
        "num_of_rooms" => 2,
        "num_of_beds" => 1,
        "num_bathrooms" => 1,
        "square_meters" => 70,
        "full_address" => "Via Enrico Avanzi, Pisa",
        "lat" =>  43.707185033799846,
        "long" => 10.419734270610805,
        "price" => 200,
        "img" => ''
    ],
    [
        "title" => "Coastal Cottage",
        "description" => "Quaint cottage by the sea, perfect for a romantic getaway.",
        "num_of_rooms" => 1,
        "num_of_beds" => 1,
        "num_bathrooms" => 1,
        "square_meters" => 60,
        "full_address" => "Via Alessandro Volta, Pisa",
        "lat" => 43.71846010122448,
        "long" => 10.396225038022031,
        "price" => 250,
        "img" => ''
    ],
    [
        "title" => "Urban Penthouse with Terrace",
        "description" => "Luxurious penthouse apartment with a spacious terrace offering panoramic city views.",
        "num_of_rooms" => 3,
        "num_of_beds" => 2,
        "num_bathrooms" => 2,
        "square_meters" => 140,
        "full_address" => "Via del Capannone, Pisa",
        "lat" => 43.71976798989642,
        "long" => 10.373352355223659,
        "price" => 400,
        "img" => ''
    ],
    [
        "title" => "Ski-In/Ski-Out Chalet",
        "description" => "Ski-in/ski-out chalet located directly on the slopes, perfect for winter sports enthusiasts.",
        "num_of_rooms" => 4,
        "num_of_beds" => 3,
        "num_bathrooms" => 2,
        "square_meters" => 180,
        "full_address" => "Via Sant'Agostino, Pisa",
        "lat" => 43.702356753437336,
        "long" => 10.397284411039958,
        "price" => 600,
        "img" => ''
    ],
    [
        "title" => "Riverside Cabin",
        "description" => "Quaint cabin nestled along the riverbank, offering a peaceful retreat in nature.",
        "num_of_rooms" => 2,
        "num_of_beds" => 1,
        "num_bathrooms" => 1,
        "square_meters" => 80,
        "full_address" => "Via Santa Maria, Pisa",
        "lat" => 43.722767398722214,
        "long" => 10.401975061169583,
        "price" => 300,
        "img" => ''
    ],
    [
        "title" => "Downtown Studio Apartment",
        "description" => "Compact studio apartment in the heart of downtown, close to shops and restaurants.",
        "num_of_rooms" => 1,
        "num_of_beds" => 1,
        "num_bathrooms" => 1,
        "square_meters" => 50,
        "full_address" => "Via Santa Caterina, Pisa",
        "lat" => 43.72494496430022,
        "long" => 10.392553864826777,
        "price" => 150,
        "img" => ''
    ]
];
